/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface YellowPredictionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMarket"
      | "getMarket"
      | "isExpired"
      | "isSettled"
      | "markRefundable"
      | "marketCount"
      | "markets"
      | "settleMarket"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketCreated"
      | "MarketRefundable"
      | "MarketSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createMarket",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isSettled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markRefundable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleMarket",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMarket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSettled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markRefundable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleMarket",
    data: BytesLike
  ): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    question: string,
    expiresAt: BigNumberish,
    creator: AddressLike,
    createdAt: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    question: string,
    expiresAt: bigint,
    creator: string,
    createdAt: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    question: string;
    expiresAt: bigint;
    creator: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketRefundableEvent {
  export type InputTuple = [marketId: BigNumberish, markedAt: BigNumberish];
  export type OutputTuple = [marketId: bigint, markedAt: bigint];
  export interface OutputObject {
    marketId: bigint;
    markedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketSettledEvent {
  export type InputTuple = [
    marketId: BigNumberish,
    outcome: BigNumberish,
    settledAt: BigNumberish
  ];
  export type OutputTuple = [
    marketId: bigint,
    outcome: bigint,
    settledAt: bigint
  ];
  export interface OutputObject {
    marketId: bigint;
    outcome: bigint;
    settledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YellowPredictionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): YellowPredictionRegistry;
  waitForDeployment(): Promise<this>;

  interface: YellowPredictionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMarket: TypedContractMethod<
    [question: string, expiresAt: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getMarket: TypedContractMethod<
    [marketId: BigNumberish],
    [
      [string, bigint, string, boolean, bigint, bigint] & {
        question: string;
        expiresAt: bigint;
        creator: string;
        settled: boolean;
        outcome: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  isExpired: TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;

  isSettled: TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;

  markRefundable: TypedContractMethod<
    [marketId: BigNumberish],
    [void],
    "nonpayable"
  >;

  marketCount: TypedContractMethod<[], [bigint], "view">;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, bigint, bigint] & {
        question: string;
        expiresAt: bigint;
        creator: string;
        settled: boolean;
        outcome: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  settleMarket: TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [question: string, expiresAt: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish],
    [
      [string, bigint, string, boolean, bigint, bigint] & {
        question: string;
        expiresAt: bigint;
        creator: string;
        settled: boolean;
        outcome: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExpired"
  ): TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isSettled"
  ): TypedContractMethod<[marketId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "markRefundable"
  ): TypedContractMethod<[marketId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "marketCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, boolean, bigint, bigint] & {
        question: string;
        expiresAt: bigint;
        creator: string;
        settled: boolean;
        outcome: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "settleMarket"
  ): TypedContractMethod<
    [marketId: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketRefundable"
  ): TypedContractEvent<
    MarketRefundableEvent.InputTuple,
    MarketRefundableEvent.OutputTuple,
    MarketRefundableEvent.OutputObject
  >;
  getEvent(
    key: "MarketSettled"
  ): TypedContractEvent<
    MarketSettledEvent.InputTuple,
    MarketSettledEvent.OutputTuple,
    MarketSettledEvent.OutputObject
  >;

  filters: {
    "MarketCreated(uint256,string,uint256,address,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketRefundable(uint256,uint256)": TypedContractEvent<
      MarketRefundableEvent.InputTuple,
      MarketRefundableEvent.OutputTuple,
      MarketRefundableEvent.OutputObject
    >;
    MarketRefundable: TypedContractEvent<
      MarketRefundableEvent.InputTuple,
      MarketRefundableEvent.OutputTuple,
      MarketRefundableEvent.OutputObject
    >;

    "MarketSettled(uint256,uint8,uint256)": TypedContractEvent<
      MarketSettledEvent.InputTuple,
      MarketSettledEvent.OutputTuple,
      MarketSettledEvent.OutputObject
    >;
    MarketSettled: TypedContractEvent<
      MarketSettledEvent.InputTuple,
      MarketSettledEvent.OutputTuple,
      MarketSettledEvent.OutputObject
    >;
  };
}
